# Generated by Django 3.0.3 on 2020-04-14 11:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_auto_20200409_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 14, 11, 50, 3, 808142)),
        ),
        migrations.AlterField(
            model_name='article',
            name='article_rating',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
