# Generated by Django 3.0.3 on 2020-04-14 12:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_auto_20200414_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 14, 12, 39, 8, 109738)),
        ),
        migrations.AlterField(
            model_name='article',
            name='article_rating',
            field=models.IntegerField(null=True),
        ),
    ]
