# Generated by Django 3.0.3 on 2020-05-15 08:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_auto_20200513_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 15, 8, 28, 17, 95341)),
        ),
    ]
